//
// Created by Oleksandr Degtiar on 21.10.2020.
//

#ifndef ZD50_POWERCONTROL
#define ZD50_POWERCONTROL

#include <Arduino.h>

#include "Config.h"
#include "avr/io.h"

#define POWER_OFF() ( PWR_PORT &= ~PWR_PINS_MASK )
#define POWER_SWITCHING_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOFTSTART | PWR_PIN_SOURCE_ON )
#define POWER_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_ON | PWR_PIN_SOURCE_ON )
#define POWER_PRE_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_ON | PWR_PIN_SOFTSTART| PWR_PIN_SOURCE_ON )
#define POWER_SWITCHING_OFF() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOFTSTART | PWR_PIN_SOURCE_ON )
#define POWER_ON_SOURCE_ONLY() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOURCE_ON )
#define IS_MAIN_POWER_ON() ( (bool)(PWR_PORT & (PWR_PIN_ON | PWR_PIN_SOFTSTART)) )

#endif //ZD50_POWERCONTROL
