//
// Created by Oleksandr Degtiar on 21.10.2020.
//

#ifndef ZD50_POWERCONTROL
#define ZD50_POWERCONTROL

#include <Arduino.h>

#ifdef __AVR_ATmega324PA__

#include "avr/io.h"

#define PWR_PIN_SOFTSTART _BV(4)
#define PWR_PIN_ON _BV(5)
#define PWR_PIN_SOURCE_ON _BV(6)
#define PWR_PINS_MASK (PWR_PIN_SOFTSTART | PWR_PIN_ON | PWR_PIN_SOURCE_ON)
#define PWR_PORT PORTA
#define POWER_INIT() DDRA |= PWR_PINS_MASK

#define POWER_OFF() ( PWR_PORT &= ~PWR_PINS_MASK )
#define POWER_SWITCHING_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOFTSTART | PWR_PIN_SOURCE_ON )
#define POWER_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_ON | PWR_PIN_SOURCE_ON )
#define POWER_SWITCHING_OFF() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOFTSTART | PWR_PIN_SOURCE_ON )
#define POWER_ON_SOURCE_ONLY() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOURCE_ON )
#define IS_MAIN_POWER_ON() ( (bool)(PWR_PORT & (PWR_PIN_ON | PWR_PIN_SOFTSTART)) )


//#define POWER_MODE_SOFTSTART() PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOFTSTART | PWR_PIN_SOURCE_ON
//#define POWER_MODE_ON() PORTA = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_ON | PWR_PIN_SOURCE_ON
//#define POWER_MODE_SOURCE_ON() ( PWR_PORT = (PWR_PORT & ~PWR_PINS_MASK) | PWR_PIN_SOURCE_ON )

#endif

#endif //ZD50_POWERCONTROL
